repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: local
    hooks:
      - id: build
        name: Build
        entry: hugo
        language: system
        args: ["build"]
        stages: [pre-push]
default_install_hook_types: [pre-commit, pre-push]
